# Impostare DOCKER_PASSWORD e DOCKER_USERNAME come 'Environment Variables' in Travis CI
# Crea (o se gi√† presente, aggiorna) un'immagine Docker contenente tutte le dipendenze necessarie al framework presso il repository locato all'indirizzo:
# https://hub.docker.com/r/DOCKER_USERNAME/prova

env:
  global:
    - CI_NAME:travis-pro

sudo: required

language: python

python:
  - "3.8"

cache: pip

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker pull $DOCKER_USERNAME/prova:latest
      - docker build --cache-from $DOCKER_USERNAME/prova:latest -t prova Dockerfile
      - docker images
      - docker tag prova $DOCKER_USERNAME/prova
      - docker push $DOCKER_USERNAME/prova
    - stage: test
      script:
      - docker run --rm $DOCKER_USERNAME/prova
  
git:
  depth: false
